# Guide the user through CF R2 setup for the snapshot pipeline.
# R2 doesn't have a single CLI command for bucket-create + api-token-issue,
# so this is a guided walkthrough rather than full automation. After
# running this, paste the printed values into mise.local.toml + fnox.

print "──── Cloudflare R2 bootstrap ────"
print ""
print "Why R2?"
print "  - Free egress: Vultr's snapshot create-url fetches via WAN; R2 doesn't charge."
print "  - Provider-neutral: same bucket works for cross-provider transfers (Hetzner → Vultr, vice versa)."
print "  - Already in your CF ecosystem (matches scrapers-proxy)."
print ""

print "Step 1 — Create an R2 bucket"
print ""
print "  Dashboard: https://dash.cloudflare.com → R2 → Create bucket"
print "  Name suggestion: 'vm-uncloud-snapshots' (or whatever fits your accounts)"
print "  Location hint: 'WNAM' for North America, 'EEUR' for Europe etc. — pick close to your VMs."
print ""
print "Step 2 — Find your R2 S3 endpoint URL"
print ""
print "  After creating the bucket, the bucket-details panel shows:"
print "    S3 API: https://<account-id>.r2.cloudflarestorage.com"
print "  Copy that. It's your R2_ENDPOINT."
print ""
print "Step 3 — Create an R2 API token"
print ""
print "  Dashboard: https://dash.cloudflare.com → R2 → Manage R2 API Tokens → Create API Token"
print "  Permissions: 'Object Read & Write'"
print "  Scope: 'Apply to specific buckets' → select the bucket from Step 1"
print "  TTL: leave default (forever) or set per your policy"
print ""
print "  Copy the Access Key ID and Secret Access Key — Cloudflare only shows the secret ONCE."
print ""
print "Step 4 — Paste into mise.local.toml + fnox"
print ""
print "  Edit mise.local.toml and add:"
print "    [env]"
print "    R2_ENDPOINT = \"https://<account-id>.r2.cloudflarestorage.com\""
print "    R2_BUCKET = \"vm-uncloud-snapshots\""
print ""
print "  Then store the credentials:"
print "    fnox set -p keychain R2_ACCESS_KEY_ID"
print "    fnox set -p keychain R2_SECRET_ACCESS_KEY"
print ""
print "Step 5 — Verify"
print ""
print "  mise run r2:check"
print ""
print "  This will do a probe PUT/GET/DELETE against the bucket to confirm credentials work."
print ""
print "──── Done ────"
